### ISSUE TITLE
ReferenceError: FlareTail is not defined

### ISSUE THREAD

**Issue by daleharvey** [kyoshino/bzdeck#216]
I tried to get this up and running with a simple

```
$ cd webroot/
$ python -m SimpleHTTPServer
```
The UI looks different and there are quite a few errors when loading `index.html`, `/scripts/libs/` doesnt exist. I tried a `git submodule add / update` but they didnt do anything

**Comment by kyoshino** [comment]
Ah, okay, I'll add an instruction shortly.

**Comment by kyoshino** [comment]
Added: https://github.com/kyoshino/bzdeck
I'm just using symlinks instead of submodules ;-)

**Comment by daleharvey** [comment]
How do you think this should be `fixed`, either embedding flaretail in bzdeck, or put the flaretail assets in an npm package and give bzdeck a package.json, or can refactor flaretail to be a proper requireable module.

I think just putting them in an npm package so we can `npm install` inside bzdeck and have 

    <script src="node_modules/flaretail/app.js"></script>

Would be the least intrusive?

**Comment by kyoshino** [comment]
I agree that symlinks require extra steps to setup, though they works well. I'm not so familiar with Git but [`git subtree`](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/) looks good and simple. It is hard to simultaneously develop subprojects using `git submodule`.
