### ISSUE TITLE
Implement API Key auth on the sign-in form

### ISSUE THREAD

**Issue by kyoshino** [kyoshino/bzdeck#217]
Currently the landing page only asks the user name but it might be better to have the API key as well so the user can start contributing right away. I still don't want to ask their passwords.

Cc @daleharvey

**Comment by daleharvey** [comment]
Cant we have the user login as they do on https://bugzilla.mozilla.org/ ?

**Comment by kyoshino** [comment]
Yes we can, as the [document](http://bugzilla.readthedocs.org/en/latest/api/core/v1/general.html#authentication) says, but I'm just uncomfortable with asking their passwords.

**Comment by daleharvey** [comment]
Would you accept a PR to? setting a token should be possible but its a much easier workflow for users to just be able to login. We can login and pick up a token so we wont be storing a password in any way

**Comment by kyoshino** [comment]
Even if BzDeck comes with dogfood builds, this is a third party app, so I still would like to avoid asking a password directly. I know it might be difficult to provide a long API key on mobile, but a key can be easily revoked by user and is a better security practice, I believe.

**Comment by kyoshino** [comment]
I remember one more reason why I do/can not support username/password auth: it may not work for people who are signing into Bugzilla with their Persona accounts.

**Comment by markrcote** [comment]
To summarize a conversion on irc.mozilla.org today, the BMO team is thinking about various solutions for the API copy/paste problem, such as a Bugzilla page that apps could redirect to, which would ask you to log into Bugzilla, then generate an API key and pass it back to the app. We're still hashing out the details, but it seems like a direction we want to take.

**Comment by kyoshino** [comment]
As I said on IRC, QR code auth might be user-friendly on mobile. I know LINE has such a [QR code login ability](http://help.line.me/line/win/categoryId/10000371/pc?lang=en) and there is a [QR code scanner for Firefox OS](http://youtu.be/6GR1vPijrnE) as well.

How it (probably) works:

1. User opens Bugzilla's API Key page on desktop
2. Bugzilla displays the QR-encoded API Key
3. User launches BzDeck on mobile and scan the QR code using the camera
4. BzDeck decodes it and authenticates against the Bugzilla API with the decoded key

**Comment by kyoshino** [comment]
Filed a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1138772) for QR code auth.
