### ISSUE TITLE
Allow opening the bug in bugzilla

### ISSUE THREAD

**Issue by shinglyu** [kyoshino/bzdeck#226]
I know we should encourage the user to use the new UI, but before all the major functions are covered in the new UI, the user should have a little link or icon to go back to the original bugzilla UI to perform some critical actions (e.g. mark the bug as RESOLVED FIXED).

**Comment by kyoshino** [comment]
:+1:

**Comment by kyoshino** [comment]
Blocker: https://github.com/kyoshino/flaretail.js/issues/24
