### ISSUE TITLE
Bug detail failed to load

### ISSUE THREAD

**Issue by shinglyu** [kyoshino/bzdeck#246]
Bug detail failed to load. 

JavaScript console shows the following error:
```
TypeError: this.view.$container is null                combined.js:2267:2
```

**Comment by kyoshino** [comment]
Confirmed on production with a clean storage. Will take a look...

**Comment by kyoshino** [comment]
Looks like the latest changes have not been deployed to production properly. Pushed (just rsynced) files and confirmed that the issue is gone.
